### ISSUE TITLE
Sorting step only partially successful

### ISSUE THREAD

**Issue by laurenhamm** [bergmanlab/TELR#21] opened 2022-10-15 19:06 UTC
When running TELR, my job is failing with the following series of errors:
```
Error: Sorted input specified, but the file /path/to/intermediate_files/vcf_ins_repeatmask/1034.vcf_ins.fasta.out.gff has the following out of order record
scaffold_10_14852480_14852481   RepeatMasker    similarity      763     858      15.9    -       .       Target "Motif:rnd-1_family-746" 962 1060
[W::fai_get_val] Reference scaffold_10_121912_121922 not found in file, returnin
g empty sequence
[faidx] Failed to fetch sequence in scaffold_10_121912_121922
...
##The [W::fai_get_val] and [faidx] repeat over an over again for different sequences###
...
[faidx] Failed to fetch sequence in scaffold_1094_7791_7792
Warning: the index file is older than the FASTA file.
Warning...unknown stuff <
>
Traceback (most recent call last):
  File "/global/home/users/laurenhamm/.local/bin/telr", line 8, in <module>
    sys.exit(main())
  File "/global/home/users/laurenhamm/.local/lib/python3.6/site-packages/telr/telr.py", line 129, in main
    args.thread,
  File "/global/home/users/laurenhamm/.local/lib/python3.6/site-packages/telr/TELR_te.py", line 588, in get_af
    vcf_parsed, out, sample_name, bam, raw_reads, telr_reads_dir, read_type="all"
  File "/global/home/users/laurenhamm/.local/lib/python3.6/site-packages/telr/TELR_assembly.py", line 405, in prep_assembly_inputs
    for read in samfile.fetch(ins_chr, start, end):
  File "pysam/libcalignmentfile.pyx", line 1082, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 690, in pysam.libchtslib.HTSFile.parse_region
ValueError: start out of range (-100)
```

The reads that faidx is failing to find in the gff file all come from scaffolds that start with "scaffold_10*", so it looks like the sorting doesn't like over 9 scaffolds? However, I don't think that this is the full problem as not all reads from those scaffolds seem to be flagged as errors. Could this be an internal indexing/sorting error?

**Comment by shunhuahan** [comment] 2022-11-02 05:39
Hi @laurenhamm,

Thanks for sharing the intermediate files. I thin the issue is caused by RepeatMasker sometimes generating out of sort GFF files. I have now included a sorting step to make sure the GFF file is correctly sorted before the downstream analysis. The pull request is now merged into the main branch (https://github.com/bergmanlab/TELR/commit/96fe6716e5d94fff0f8f221a80e86457bf6689a4).

Can you try re-installing TELR using the alternative way mentioned in https://github.com/bergmanlab/TELR/blob/master/docs/01_Installation.md#install-telr and see if the new build has the issue resolved in your case? Thanks.
```
git clone git@github.com:bergmanlab/TELR.git
cd TELR
mamba env create -f envs/telr.yml
conda activate TELR
pip install .
```

Best,
Shunhua

**Comment by renhamm** [comment] 2022-11-21 18:16
I re-downloaded TELR, and I'm still hitting a weird sorting error. Here is the error:

```
[M::main] CMD: minimap2 --cs --MD -Y -L -ax map-pb /global/scratch/users/laurenhamm/thesis/TELR_annotations/TELR_REINSTALL/intermediate_files/Mguttatus_256_v2.0.fa /global/scratch/users/laurenhamm/thesis/TELR_annotations/TELR_REINSTALL/intermediate_files/1034.fastq
[M::main] Real time: 77566.709 sec; CPU: 235628.350 sec; Peak RSS: 7.353 GB
[bam_sort_core] merging from 1128 files and 24 in-memory blocks...
[W::vcf_parse] FILTER 'STRANDBIAS' is not defined in the header
Warning...unknown stuff <
>
Error: Sorted input specified, but the file /global/scratch/users/laurenhamm/thesis/TELR_annotations/TELR_REINSTALL/intermediate_files/vcf_ins_repeatmask/1034.vcf_ins.fasta.out.gff has the following out of order record
scaffold_10_14852480_14852481   RepeatMasker    similarity      763     858     15.9    -       .       Target "Motif:rnd-1_family-746" 962 1060
Warning...unknown stuff <
>
Traceback (most recent call last):
  File "/global/home/users/laurenhamm/.local/bin/telr", line 8, in <module>
    sys.exit(main())
  File "/global/home/users/laurenhamm/.local/lib/python3.6/site-packages/telr/telr.py", line 129, in main
    args.thread,
  File "/global/home/users/laurenhamm/.local/lib/python3.6/site-packages/telr/TELR_te.py", line 588, in get_af
    vcf_parsed, out, sample_name, bam, raw_reads, telr_reads_dir, read_type="all"
  File "/global/home/users/laurenhamm/.local/lib/python3.6/site-packages/telr/TELR_assembly.py", line 405, in prep_assembly_inputs
    for read in samfile.fetch(ins_chr, start, end):
  File "pysam/libcalignmentfile.pyx", line 1082, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 690, in pysam.libchtslib.HTSFile.parse_region
ValueError: start out of range (-100)
```

**Comment by shunhuahan** [comment] 2022-12-06 04:17
@laurenhamm sorry for the late response!

- Based on the error log, it looks to me the updated TELR is not being used (the repeatmasker gff is still not sorted). Could you confirm that you have pulled the update in the TELR git repo and installed the updated version locally using `pip` before the test run? Thanks! If the update is working for you, I will include it in the future conda release so there will be no need for the pip install.

```sh
mamba env create -f envs/telr.yml # not necessary if you have already installed the TELR conda environment
conda activate TELR

cd TELR # this is the TELR git folder
git pull # necessary to use this patched update
pip install . # necessary to use this patched update
```

Best,
Shunhua

**Comment by renhamm** [comment] 2023-02-27 20:15
I reinstalled the new update, and it ran for ~3 days before failing with the following error in the bam merging step:

```
[M::main] CMD: minimap2 --cs --MD -Y -L -ax map-pb /global/scratch/users/laurenhamm/thesis/TELR_annotations/TELR_newOut/intermediate_files/Mguttatus_256_v2.0.fa /global/scratch/users/laurenhamm/thesis/TELR_annotations/TELR_newOut/intermediate_files/1034.fastq
[M::main] Real time: 81175.678 sec; CPU: 247043.607 sec; Peak RSS: 6.983 GB
[bam_sort_core] merging from 1128 files and 24 in-memory blocks...
[W::vcf_parse] FILTER 'STRANDBIAS' is not defined in the header
Warning...unknown stuff <
>

**Comment by shunhuahan** [comment] 2023-02-28 01:32
Hi @laurenhamm,

Thanks for sharing the follow up experiment. The log doesn't seem to contain any informative error message that can help me determine the cause of the issue. Could you share the full log? Btw, was TELR taking this long in your previous experiment?

If your input files are not crazy large and can be shared, could you upload the files to google drive and share with hanshunhua0829@gmail.com? To help reduce the file size, you could consider subsetting the BAM file to only include reads aligning to a single chromosome/small region in the reference but can still generate the error.  I'm happy to take a close look and check if the issue is still coming from a bug or if TELR is not compatible with your input data.

Thanks,
Shunhua

**Comment by cbergman** [comment] 2023-05-03 15:37
Hi @laurenhamm 

From what we can tell, you currently have a working installation of TELR on your machine, which includes the fix to the repeatmasker sorting problem you identified. If not, you should be able to install TELR v1.1 via bioconda as follows:
```
mamba create -n TELR --channel bioconda telr=1.1
```

Since the original bug you reported in this issue has been resolved, I am going to close this issue. 

If you are still having trouble running TELR on your data as indicated in https://github.com/bergmanlab/TELR/issues/21#issuecomment-1447020252, please open a new issue and we can discuss more there.

Best regards,
Casey

**Closed by cbergman** 2023-05-03 15:37 UTC
